### ISSUE TITLE
rabbitmq_config error generating single quote value

### ISSUE THREAD

**Issue by Raffaello** [jasonroyle/ansible-role-rabbitmq#4]
the library `config-encoder-macros` is not able to generate single quote value for rabbitmq config, it means it will generate wrong configuration file. 

It leads to not possible to configure correctly rabbitmq.

e.g.:

```
rabbitmq_config:
      - rabbit:
        - ssl_listeners:
          - 5671
        - ssl_options:
          - versions:
            - 'tlsv1.2'
```

the output is:

```
%
% This file is managed by Ansible.
% Do not edit this file manually.
% Any changes will be automatically reverted.
%

[
  {rabbit, [
      {ssl_listeners, [
        5671
      ]},
      {ssl_options, [
          {versions, [
            "tlsv1.2"
          ]}
      ]}
  ]}
].
```

please notice `"tlsv1.2"` instead of `'tlsv1.2'`
double quoted instead of single quoted.

and it is invalid config for rabbitmq
